config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'list' => 'articles#list'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def list
    @articles = Article.all
  end

  def new
  end 

  def create
    @article = Article.new(article_params)
 
    @article.save
    redirect_to @article
  end

private
  def article_params
    params.require(:article).permit(:title, :author, :year, :coop, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Year</th>
    <th>Coop</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, url_for({controller: 'articles', action: 'show', id: article.id}) %></td>
      <td><%= article.author %></td>
      <td><%= article.year %></td>
      <td><%= article.coop %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

app/views/articles/list.html.erb
<h1>List of articles</h1>

<%= react_component('HelloMessage', {name: 'John'}, {prerender: true}) %>
 
<%= react_component('articles', {articles: @articles}, {prerender: true}) %>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Year</th>
    <th>Coop</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, url_for({controller: 'articles', action: 'show', id: article.id}) %></td>
      <td><%= article.author %></td>
      <td><%= article.year %></td>
      <td><%= article.coop %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </p>

  <p>
    <%= f.label :coop %><br>
    <%= f.text_field :coop %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>
<p>
  <strong>Year:</strong>
  <%= @article.year %>
</p>
<p>
  <strong>Coop:</strong>
  <%= @article.coop %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reactest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'async' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<p>
  <%= link_to 'My Blog', controller: 'articles' %>
</p>

<p>
  <%= link_to 'New article', new_article_path %>
</p>